/*本关任务（习题5.11）：n0是一个给定的正整数，对于i=0，1，2...，定义：
（1）若ni是偶数，则ni+1 =ni/2；
（2）若ni是奇数，则ni+1 =3ni +1；
（3）若ni是1，则序列结束。
用该方法产生的数称为冰雹(hailstone)。
编写产生一些冰雹的程序，程序应该用函数void hailstone(int n)；计算冰雹并显示由n产生的序列。程序的输出见:<测试说明>*/
#include <stdio.h>

//请根据主程序流程，补全此函数
//冰雹产生并输出函数
//注意：输出每个冰雹数时，请按5位对齐输出
void hailstone(int n) 
{
    printf("Hailstone generated by %d:\n",n);
    /**********  Begin **********/
    printf("%5d",n);
    for(int i=0;;i++){
        if(n==1){
            printf("%5d",n);
            break;
        }
        if(n%2==0){
            n=n/2;
            printf("%5d",n);
        }
        if(n%2==10){
            n=3*n+1;
            printf("%5d",n);
        }
        if((i+1)%6==0){
            printf("\n");
        }

    /**********  End  **********/
    printf("%5d\n",n);
	printf("Number of hailstone generated:%d",count);
}
#include <stdio.h>
#include "step2_stu.h"

//请根据此函数补全文件step2_stu.h中冰雹产生函数
int main()
{
    int number;

    printf("input a number:");
    scanf("%d", &number);

    hailstone(number);

    return 0;
}